name: update-clock-corrections
on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '23 20 * * *'
jobs:
    run-update-script:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: pip install -r requirements.txt
            - run: git clone https://github.com/ipta/pulsar-clock-corrections.git  --branch gh-pages --single-branch /tmp/gh-pages --depth 1
            - run: python update_clock_corrections.py --gh-pages /tmp/gh-pages
            - run: |
                git config --global user.name "Anne Archibald"
                git config --global user.email 'aarchiba@users.noreply.github.com'
                git add tempo T2runtime log
                git commit -am "Routine repo update from Github action `date`"
                git log -n 1
                git push
            - run: |
                cd /tmp/gh-pages 
                git add .
                git commit -am "Routine gh-pages update from Github action `date`"
                git log -n 1
                git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
                git push


